
-- Stock & Distribution
CREATE TABLE Country (
    CountryID SMALLINT PRIMARY KEY,
    Name NVARCHAR(500) NOT NULL,
    isEU BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE Shop (
    ShopID INT PRIMARY KEY,
    Name NVARCHAR(1000) NOT NULL,
    City NVARCHAR(1000) NOT NULL,
    Long FLOAT NOT NULL,
    Lat FLOAT NOT NULL,
    CountryID SMALLINT,
    AddressID INT,
    FOREIGN KEY (CountryID) REFERENCES Country(CountryID)
);

-- Sales
CREATE TABLE Payment (
    PaymentID UUID PRIMARY KEY,
    TotalAmount MONEY,
    CreateDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ShopID INT,
    DateDetailsID DATE,
    CustomerCategoryID INT,
    FOREIGN KEY (ShopID) REFERENCES Shop(ShopID),
    FOREIGN KEY (DateDetailsID) REFERENCES DateDetails(DateDetailsID),
    FOREIGN KEY (CustomerCategoryID) REFERENCES CustomerCategory(CustomerCategoryID)
);

CREATE TABLE PaymentDetail (
    PaymentDetailID UUID PRIMARY KEY,
    Quantity NUMERIC(8,2) NOT NULL,
    DiscountValue MONEY,
    FinalValue MONEY,
    PaymentID UUID,
    DiscountID SMALLINT,
    ProductID UUID,
    FOREIGN KEY (PaymentID) REFERENCES Payment(PaymentID),
    FOREIGN KEY (DiscountID) REFERENCES Discount(DiscountID),
    FOREIGN KEY (ProductID) REFERENCES Product(ProductID)
);

-- Manufacturing
CREATE TABLE Supplier (
    SupplierID INT GENERATED BY DEFAULT AS IDENTITY (START WITH 3000 INCREMENT BY 1) PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL
);

CREATE TABLE Product (
    ProductID UUID PRIMARY KEY,
    ProductName NVARCHAR(255) NOT NULL,
    SupplierID INT,
    Unit NVARCHAR(3) NOT NULL,
    UnitPrice FLOAT NOT NULL,
    ProductCategoryID INT,
    FOREIGN KEY (SupplierID) REFERENCES Supplier(SupplierID),
    FOREIGN KEY (ProductCategoryID) REFERENCES ProductCategory(ProductCategoryID)
);

CREATE TABLE ProductCategory (
    ProductCategoryID SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL
);

-- Marketing
CREATE TABLE DateDetails (
    DateDetailsID DATE PRIMARY KEY,
    IsHoliday BOOLEAN NOT NULL DEFAULT FALSE,
    WeekDay SMALLINT NOT NULL
);

CREATE TABLE CustomerCategory (
    CustomerCategoryID INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    Gender NVARCHAR(1),
    AgeCategory NVARCHAR(8) NOT NULL
);

CREATE TABLE Discount (
    DiscountID SMALLINT PRIMARY KEY,
    Name NVARCHAR(1000) NOT NULL,
    Amount NUMERIC(4,2) NOT NULL
);
