version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: retail_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: retail-be
    ports:
      - "5432:5432"
    networks:
      - retail-net

  retail_be_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/retail-be
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
    ports:
      - "8080:8080"
    networks:
      - retail-net

networks:
  retail-net:
