spring:
  application:
    name: retail-be

  datasource:
    url: jdbc:postgresql://localhost:5432/retail-be
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: false
